language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
before_install:
  - "cpanm -n Dist::Zilla"
install:
  - "sudo apt-get update"
  - "sudo apt-get install aspell aspell-en"
  - "dzil authordeps --missing | cpanm -n -q"
  - "dzil listdeps --missing | cpanm -n -q"
script: "dzil smoke --release --author"
